2025-04-18 14:56:52,811 ERROR: Exception on /explore [GET] [in /mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/routes.py", line 169, in explore
    return render_template("index.html", title='Explore', posts=posts.items,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/index.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/base.html", line 60, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/index.html", line 13, in block 'content'
    {{form.hidden_tag()}}
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-04-18 15:00:15,712 ERROR: Exception on /user/admin [GET] [in /mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/routes.py", line 88, in user
    return render_template('user.html', user=user, posts=posts.items,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/user.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/base.html", line 60, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/user.html", line 44, in block 'content'
    {{form.hidden_tag()}}
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2025-04-18 15:03:27,687 INFO: Microblog startup [in /mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/__init__.py:57]
2025-04-18 15:03:31,573 ERROR: Exception on /user/admin [GET] [in /mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/routes.py", line 88, in user
    return render_template('user.html', user=user, posts=posts.items,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/user.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/base.html", line 60, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/templates/user.html", line 44, in block 'content'
    {{form.hidden_tag()}}
  File "/mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'hidden_tag'
2025-04-18 15:06:46,986 INFO: Microblog startup [in /mnt/c/Users/DELL/Desktop/blog/my_blog_site_on_flask/app/__init__.py:57]
